version: '3'

services:
  db:
    image: postgres
    volumes:
    - pgdata:/var/lib/postgresql/data
  web:
    build: ./backend
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - elasticsearch
    command: bash -c "./wait-for-it.sh db:5432 && python3 manage.py runserver 0.0.0.0:8000"
    links:
      - redis
  redis:
    image: redis:latest
    ports:
     - "6379:6379"
  front:
    build: ./frontend
    command: npm start
    volumes:
      - ./frontend:/src
      - node_modules:/src/node_modules
    ports:
      - 3000:3000
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
volumes:
  pgdata:
  esdata:
  node_modules: